[project]
name = "mcp-eventbrite"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "asyncio>=3.4.3",
    "fastmcp>=2.5.2",
    "httpx>=0.28.1",
]
